// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package index

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"pt-BR\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Projetos Sustentáveis</title><script src=\"https://cdn.tailwindcss.com\"></script><script src=\"https://unpkg.com/htmx.org@1.9.5\"></script><link href=\"https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css\" rel=\"stylesheet\"></head><body class=\"bg-purple-100 p-4 min-h-screen flex items-center justify-center\"><div class=\"container mx-auto max-w-4xl bg-white p-6 rounded-xl shadow-lg\"><h1 class=\"text-4xl font-bold text-center text-purple-700 mb-6\">Projetos Sustentáveis</h1><div class=\"flex justify-center space-x-4 mb-4\"><button class=\"bg-purple-600 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded transition\" hx-get=\"/api/projetos\" hx-trigger=\"click\" hx-target=\"#projetos-lista\">Carregar Projetos</button></div><div id=\"projetos-lista\" class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4\"><!-- Projetos serão carregados aqui --></div><div class=\"mt-6 text-center\"><p class=\"text-gray-700\">Entre com:</p><div class=\"flex justify-center space-x-4 mt-2\"><a href=\"/auth/google\" class=\"bg-red-600 hover:bg-red-700 text-white py-2 px-4 rounded transition\">Login com Google</a> <a href=\"/auth/github\" class=\"bg-gray-800 hover:bg-gray-900 text-white py-2 px-4 rounded transition\">Login com GitHub</a></div></div></div><script src=\"https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
