// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Nav(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"bg-gradient-to-r from-orange to-golden dark:from-gray-800 dark:to-gray-700 px-4 py-4 shadow-xl top-0 w-full z-50\"><div class=\"container mx-auto flex items-center justify-between\"><!-- Logo e Nome --><div class=\"flex-1 flex items-center space-x-3\"><image src=\"/images/icons/house_with_garden.png\" alt=\"Logo\" class=\"w-10 h-10\"></image><h1 class=\"text-3xl font-bold text-white dark:text-gray-100\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/components/nav.templ`, Line: 9, Col: 84}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</h1></div><!-- Links de Navegação para Desktop --><div class=\"flex-1 hidden md:flex items-center justify-center space-x-8\"><a href=\"/\" class=\"text-white text-lg hover:text-red hover:underline hover:underline-offset-4 font-medium transition-all duration-300\">Início</a> <a href=\"/project\" class=\"text-white text-lg hover:text-green hover:underline hover:underline-offset-4 font-medium transition-all duration-300\">Projetos</a> <a href=\"/about\" class=\"text-white text-lg hover:text-blue hover:underline hover:underline-offset-4 font-medium transition-all duration-300\">Sobre</a></div><!-- Botões de Controle --><div class=\"flex-1 flex items-center justify-end space-x-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ButtonToggleTheme().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ButtonAccount().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<button id=\"mobile-menu-toggle\" class=\"md:hidden text-white p-2 rounded-lg hover:bg-orange-500/20 transition-colors\" aria-controls=\"mobile-menu\" aria-expanded=\"false\" data-collapse-toggle=\"mobile-menu\"><svg class=\"w-6 h-6\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 6h16M4 12h16m-7 6h7\"></path></svg></button></div></div><!-- Menu Mobile --><div id=\"mobile-menu\" class=\"hidden md:hidden bg-gradient-to-r from-orange to-golden dark:from-gray-800 dark:to-gray-700 shadow-lg mt-2 rounded-b-2xl\"><div class=\"container mx-auto px-4 py-6 space-y-4\"><a href=\"/\" class=\"block text-white text-lg hover:text-orange-300 hover:bg-orange-500/10 py-2 px-4 rounded-lg transition-all duration-300\" hx-get=\"/index\" hx-target=\"body\" hx-push-url=\"true\">Início</a> <a href=\"/project\" class=\"block text-white text-lg hover:text-orange-300 hover:bg-orange-500/10 py-2 px-4 rounded-lg transition-all duration-300\" hx-get=\"/projects\" hx-target=\"body\" hx-push-url=\"true\">Projetos</a> <a href=\"/about\" class=\"block text-white text-lg hover:text-orange-300 hover:bg-orange-500/10 py-2 px-4 rounded-lg transition-all duration-300\" hx-get=\"/about\" hx-target=\"body\" hx-push-url=\"true\">Sobre</a></div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
